name: Terraform PR Runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Will cancel an in-progress workflow on a new push
# see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  get_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request Number
        id: pr
        run: |
          echo "pull_request_number=$(if [ '${{ github.event_name }}' = 'pull_request' ]; then echo ${{ github.event.number }}; else echo $(gh pr list --state merged --limit 1 --json number -q '.[0] | .number'); fi)" >> $GITHUB_OUTPUT
    outputs:
      pull_request_number: ${{ steps.pr.outputs.pull_request_number }}

  plan_and_apply:
    needs:
      - get_pr
    uses: ./.github/workflows/deploy_all.yml
    secrets: inherit
